### PR TITLE
Update SN2005fk.json

### PR DESCRIPTION
**Pull request by annayqho**
SN2005fk received as Ic-BL classification in Taddia et al. (2015). I have added this classification as well as the reference. When I clicked "edit" on the homepage I was taken to creating this new .json page, though, instead of editing an existing one -- I am not sure why that is.

### CODE REVIEW

**Comment by guillochon** [comment]
In this case, it's because there was no user-provided data for this particular SNe.

**Comment by guillochon** [comment]
Currently this is not valid JSON, missing some commas.

**Comment by annayqho** [comment]
Oops, sorry. Should I make this change myself? (Apologies, I am new to this!)

**Comment by guillochon** [comment]
Yes please!

**Pull request merged**
