### PR TITLE
Update SN1995bd.json

### PR DESCRIPTION
**Pull request by lgalbany**
Claimed as 91T-like in Garnavich et al. 1996 and Saha et al. 2001

### CODE REVIEW

**Review by guillochon — CHANGES_REQUESTED** [review]
Hi @lgalbany, few issues with the edit:

- Each bibcode needs a separate source entry, create two sources each with its own bibcode.
- When you have two sources, they need to be tagged with an "alias" attribute in addition to "bibcode", this is a single number for each source, e.g. "alias":"1".
- To ensure the typing gets attributed to both sources, append a "source" attribute to the claimedtype that's a comma-delimited list: "source":"1,2"
- Please remove the "e_value" and "u_value" attributes, they don't apply to "claimedtype".

**Comment by lgalbany** [comment]
thanks for the indications. All done.

**Review by guillochon — CHANGES_REQUESTED** [review]
Missing comma between alias and bibcode attributes in sources but otherwise good!

**Comment by lgalbany** [comment]
done!

**Comment by guillochon** [comment]
Thanks for all the updates @lgalbany!

**Pull request merged**
