### PR TITLE
"claimedtype" added to SN2011hr.

### PR DESCRIPTION
**Pull request by lgalbany**
Claimed as 91T in Weyant et al. 2014 and Zhang et al. 2016. Also, optical photometry available in Zhang et al. 2016

### CODE REVIEW

**Review by guillochon — CHANGES_REQUESTED** [review]
See the 1995D review, same thing for this file.

**Comment by lgalbany** [comment]
shame on me, but I do not find the 1995D review. Can you please indicate where to go?

**Comment by guillochon** [comment]
Apologies, I meant same issues as your 95bd pull request.

**Comment by lgalbany** [comment]
modified!

**Pull request merged**
